language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - gem install jbundler
rvm:
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-9.2.9.0
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - openjdk6
