repository 'https://repo1.maven.org/maven2'

jar 'org.sonatype.aether:aether-api','1.1'
jar 'nz.ac.waikato.cms.weka:weka-stable','3.6.10'
jar 'org.apache.commons:commons-math3','3.0'
jar 'junit:junit','3.8.1'
jar 'mysql:mysql-connector-java','5.1.6'
jar 'postgresql:postgresql','9.1-901.jdbc4'
jar 'org.xerial:sqlite-jdbc','3.42.0.0'
jar 'hsqldb:hsqldb','1.8.0.7'
jar 'idb:idb','3.26'
jar 'mckoi:mckoi','0.93'
