name: Test

on: [push, pull_request]

jobs:
  build:
    name: on ruby ${{matrix.ruby}}
    runs-on: ubuntu-latest
    env:
      JARS_RESOLVE: true

    strategy:
      fail-fast: false
      matrix:
        ruby: [jruby-9.3.8.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
      env:
        JARS_RESOLVE: true

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Specs
      run: bundle exec rake
